[workspace]
default-members = ["rspace"]
members = [
  "rspace",
  "core",
  "derive",
  "macros",
  "traits",
]
resolver = "3"

[workspace.package]
authors = [
  "FL03 <joe@pzzld.org> (https://github.com/FL03)",
]
categories = []
description = "rspace focuses on establishing a robust foundation for exploring and utilitizing containers, spaces, fields, and other abstractions in Rust."
edition = "2024"
homepage = "https://github.com/FL03/rspace/wiki"
keywords = ["containers", "hkt", "space", "mathematics", "science"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/FL03/rspace.git"
rust-version = "1.85.0"
version = "0.0.7"

[workspace.dependencies]
rspace = { default-features = false, path = "rspace", version = "0.0.7" }
rspace-core = { default-features = false, path = "core", version = "0.0.7" }
rspace-traits = { default-features = false, path = "traits", version = "0.0.7" }

rspace-derive = { default-features = false, path = "derive", version = "0.0.7" }
rspace-macros = { default-features = false, path = "macros", version = "0.0.7" }
# development & benchmarking
criterion = { version = "0.8" }
# concurrency & parallelism
rayon = { default-features = false, version = "1" }
rayon-core = { default-features = false, version = "1" }
# data structures
hashbrown = { default-features = false, version = "0.16" }
# error handling
anyhow = { default-features = false, version = "1" }
thiserror = { default-features = false, version = "2" }
# logging 
tracing = { default-features = false, features = ["attributes"], version = "0.1" }
tracing-subscriber = { version = "0.3" }
# math
num-complex = { default-features = false, version = "0.4" }
num-traits = { default-features = false, version = "0.2" }
# random
getrandom = { default-features = false, version = "0.3" }
rand = { default-features = false, version = "0.9" }
rand_core = { default-features = false, version = "0.9" }
rand_distr = { default-features = false, version = "0.5" }
# serialization
serde = { default-features = false, features = ["derive"], version = "1" }
serde_derive = { default-features = false, version = "1" }
serde_json = { default-features = false, version = "1" }
# macros & utilities
paste = { version = "1" }
# WebAssembly
wasm-bindgen = { default-features = false, version = "0.2" }

# ********* Profiles *********
[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = "thin"
opt-level = 2
overflow-checks = true
panic = "abort"
rpath = false
strip = "symbols"

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "z"
overflow-checks = false
panic = "abort"
rpath = false
strip = "debuginfo"
