[package]
build = "build.rs"
description = "Core modules for the rspace framework"
name = "rspace-core"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["default"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[dependencies]
rspace-traits = { workspace = true }
# data structures
hashbrown = { optional = true, workspace = true }
# mathematics
num-complex = { optional = true, workspace = true }
num-traits = { workspace = true }
# error handling
thiserror = { workspace = true }
# random
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_core = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# WebAssembly
wasm-bindgen = { optional = true, workspace = true }

[features]
default = ["std"]

full = [
  "default",
  "complex",
  "hashbrown",
  "json",
  "serde",
]

# ********* [FF] Features *********
json = [
  "alloc",
  "serde",
  "serde_json",
]

macros = []

nightly = [
  "hashbrown?/nightly",
  "rand?/nightly",
  "rspace-traits/nightly",
]

# ********* [FF] Environments *********
std = [
  "alloc",
  "rspace-traits/std",
  "hashbrown?/default",
  "num-complex?/std",
  "num-traits/std",
  "rand?/std",
  "rand_core?/std",
  "rand_distr?/std",
  "serde?/std",
  "serde_json?/std",
  "thiserror/std",
]

wasi = [
  "rspace-traits/wasi",
]

wasm = [
  "wasm_bindgen",
  "rspace-traits/wasm",
  "getrandom?/wasm_js",
]

# ********* [FF] Dependencies *********
alloc = [
  "rspace-traits/alloc",
  "hashbrown?/alloc",
  "rand?/alloc",
  "rand_distr?/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
]

complex = ["dep:num-complex"]

hashbrown = [
  "dep:hashbrown",
  "rspace-traits/hashbrown",
]

rand = [
  "rng",
  "dep:rand",
  "dep:rand_core",
  "dep:rand_distr",
  "rspace-traits/rand",
  "num-complex?/rand",
]

rayon = [
  "rspace-traits/rayon",
  "hashbrown?/rayon",
]

rng = [
  "dep:getrandom",
  "rand?/os_rng",
  "rand?/small_rng",
  "rand_core?/os_rng",
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "serde?/derive",
  "hashbrown?/serde",
  "num-complex?/serde",
  "rand?/serde",
  "rand_core?/serde",
  "rand_distr?/serde",
  "rspace-traits/serde",
]

serde_json = ["dep:serde_json"]

wasm_bindgen = [
  "dep:wasm-bindgen",
  "rspace-traits/wasm_bindgen",
]
