[package]
build = "build.rs"
name = "rspace"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
doc-scrape-examples = true
features = ["default"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"
bench = true
doctest = true
test = true

[[bench]]
name = "default"
harness = false

[[example]]
doc-scrape-examples = true
name = "space"
required-features = ["default"]

[dependencies]
rspace-core = { workspace = true }
rspace-derive = { optional = true, workspace = true }
rspace-macros = { optional = true, workspace = true }

[dev-dependencies]
criterion = { features = ["plotters"], workspace = true }
tracing = { features = ["default", "log"], workspace = true }
tracing-subscriber = { features = ["fmt", "env-filter"], workspace = true }

[features]
default = ["std"]

full = [
  "default",
  "complex",
  "derive",
  "hashbrown",
  "json",
  "rand",
  "serde",
]

# ********* [FF] Features *********
derive = [
  "dep:rspace-derive",
  "macros",
]

macros = [
  "dep:rspace-macros", 
  "rspace-core/macros",
]

nightly = [
  "rspace-core/nightly",
  "rspace-derive?/nightly",
  "rspace-macros?/nightly",
]

json = [
  "alloc",
  "serde",
  "serde_json",
  "rspace-core/json",
]

# ********* [FF] Environments *********
std = [
  "alloc",
  "rspace-core/std",
]

wasi = [
  "alloc",
  "rspace-core/wasi",
]

wasm = [
  "alloc",
  "rspace-core/wasm",
]

# ********* [FF] Dependencies *********
alloc = [
  "rspace-core/alloc",
]

complex = [
  "rspace-core/complex",
]

hashbrown = [
  "rspace-core/hashbrown",
]

rand = [
  "rspace-core/rand",
  "rng",
]

rayon = [
  "rspace-core/rayon",
]

rng = [
  "rspace-core/rng",
]

serde = [
  "rspace-core/serde",
]

serde_json = [
  "rspace-core/serde_json",
]

wasm_bindgen = [
  "rspace-core/wasm_bindgen",
]