[package]
build = "build.rs"
description = "Traits and interfaces supporting the rspace framework"
name = "rspace-traits"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
bench = false
crate-type = ["lib"]
doc = true
doctest = true
test = true

[dependencies]
# data-structures
hashbrown = { optional = true, workspace = true }
ndarray = { optional = true, workspace = true }
# mathematics
num-complex = { optional = true, workspace = true }
num-traits = { workspace = true }
# macros and utilities
paste = { workspace = true }
# WebAssembly
wasm-bindgen = { optional = true, workspace = true }

[features]
default = ["std"]

full = [
  "default",
  "complex",
  "ndarray",
  "hashbrown",
  "rand",
  "serde",
]

# ********* [FF] Features *********

nightly = [
  "hashbrown?/nightly",
]

# ********* [FF] Environments *********

std = [
  "alloc",
  "hashbrown?/default",
  "ndarray?/std",
  "num-complex?/std",
  "num-traits/std",
]

wasi = []

wasm = [
  "wasm_bindgen",
]

# ********* [FF] Dependencies *********

alloc = [
  "hashbrown?/alloc",
]

complex = ["dep:num-complex"]

hashbrown = ["dep:hashbrown"]

ndarray = ["dep:ndarray"]

rayon = [
  "hashbrown?/rayon",
]

rand = [
  "num-complex?/rand",
]

serde = [
  "hashbrown?/serde",
  "num-complex/serde",
]

wasm_bindgen = ["dep:wasm-bindgen"]
