name: cargo-build

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_call:
    inputs:
      no-default-features:
        description: "Compile the package(s) without default features"
        required: false
        type: boolean
      verbose:
        description: "Select the features to compile"
        required: false
        type: boolean
      features:
        description: "Select the features to compile"
        required: false
        type: string
      target:
        default: x86_64-unknown-linux-gnu
        description: "Select the target to compile for"
        required: true
        type: string
      toolchain:
        default: stable
        description: "Select a toolchain to test (stable, nightly, beta)"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      target:
        default: x86_64-unknown-linux-gnu
        description: "Select the target to compile for"
        required: false
        type: choice
        options:          
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
          - wasm32-wasip1
          - wasm32-wasip2          
      toolchain:
        default: stable
        description: "Select a toolchain to test (stable, nightly)"
        required: true
        type: choice
        options: [stable, nightly]

jobs:
  workspace:
    name: Build the workspace
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - features: ${{ github.event.inputs.features }}
            target: ${{ github.event.inputs.target }}
            toolchain: ${{ github.event.inputs.toolchain || 'stable' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          repository: ${{ github.repository }}
          ref: ${{ github.event.client_payload.ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup the job
        run: |
          if [[ "${{ matrix.toolchain }}" == "nightly" ]]; then
            echo "RUSTFLAGS='-C panic=abort -Z panic_abort_tests'" >> $GITHUB_ENV
          fi
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: cargo build (${{ matrix.features }})
        run: |
          cargo build --release --lib --locked --workspace \
            --features ${{ matrix.features }} \
            --target ${{ matrix.target }}
