# This workflow is used to benchmark a Rust project
name: cargo-bench
# The workflow may be manually triggered and is run automatically when:
# - a pull request is closed on the default branch (main/master)
# - a release is published
# - a repository_dispatch event with the type "cargo-bench" is received

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_call:
    inputs:
      no-default-features:
        description: "Compile the package(s) without default features"
        required: false
        type: boolean
      verbose:
        description: "Select the features to compile"
        required: false
        type: boolean
      features:
        description: "Select the features to compile"
        required: false
        type: string
      target:
        default: x86_64-unknown-linux-gnu
        description: "Select the target to compile for"
        required: true
        type: string
      toolchain:
        default: stable
        description: "Select a toolchain to test (stable, nightly, beta)"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      target:
        default: x86_64-unknown-linux-gnu
        description: "Select the target to compile for"
        required: false
        type: choice
        options:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
          - wasm32-wasip1
          - wasm32-wasip2
      toolchain:
        default: stable
        description: "Select a toolchain to test (stable, nightly)"
        required: true
        type: choice
        options: [stable, nightly]

jobs:
  workspace:
    name: Build the workspace
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
    permissions:
      contents: write
      checks: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - features: ${{ github.event.inputs.features }}
            target: ${{ github.event.inputs.target }}
            toolchain: ${{ github.event.inputs.toolchain || 'stable' }}
    outputs:
      id: ${{ steps.artifacts.outputs.artifact-id }}
      digest: ${{ steps.artifacts.outputs.artifact-digest }}
      url: ${{ steps.artifacts.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo criterion
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-criterion
      - name: Benchmark (${{ matrix.target }})
        run: cargo criterion bench --locked \
          --features ${{ matrix.features }} \
          --target ${{ matrix.target }}
      - name: Upload the benchmarks
        id: artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Benchmark Report (${{ github.run_id }})
          if-no-files-found: error
          overwrite: true
          path: target/criterion/
