name: crates

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BASENAME: ${{ github.event.repository.name }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions: write-all

jobs:
  core:
    env:
      CRATE_NAME: ${{ github.event.repository.name }}-${{ matrix.CRATE_SUFFIX }}
    name: Publish SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CRATE_SUFFIX: [ core ]
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ env.CRATE_NAME }}
  publish:
    name: Publish SDK
    needs: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ github.event.repository.name }}